name: docker

on:
  push:

jobs:
  branch:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver-opts: network=host

      - name: Build only
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: localhost:5000/slow-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: test
        run: |
          docker run localhost:5000/slow-build cat /etc/alpine-release
