name: docker

on:
  push:

jobs:
  branch:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      - name: Build only
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: Dockerfile
          tags: slow-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: test
        run: |
          docker run slow-build cat /etc/alpine-release
